### ISSUE TITLE
Django validation form

### ISSUE THREAD

**Issue by infosrabah** [dimkoug/tododjangoccb#2]
After playing arround, and made a novalidate tag into html forms to stop browser validate the form and let django does it.I noticed that there's no django validation form. it stuck at clicking the create button, the post request goes but no response.

I there a way to activate it ?

thank's

**Comment by dimkoug** [comment]
Post the code that you use

**Comment by infosrabah** [comment]
https://github.com/infosrabah/tododjangoccbv-bootstrap4-jquery3

**Comment by dimkoug** [comment]
Fixed
