### ISSUE TITLE
Add column in ajax> _list_partial

### ISSUE THREAD

**Issue by bisnard29** [dimkoug/tododjangoccb#7]
Hi Dimitris,

I would like to add some other columns in my cmslistview, showing other object attibutes but I cannot find the solution. Could you help me  to figure it out please? 
![image](https://user-images.githubusercontent.com/58581090/80945920-31c54980-8ded-11ea-9bbb-db6a99f4c479.png)
![image](https://user-images.githubusercontent.com/58581090/80945875-207c3d00-8ded-11ea-89d7-3c3b0ef5b3d6.png)

Many thanks in advance,

Benjamin

**Comment by dimkoug** [comment]
yes  if you add in your model class a new field  fo example  name2 = models......

you can access it in the template  as  {{object.name2 }}

**Comment by bisnard29** [comment]
I was sure i tried multiple times already, but it works! thanks for the quick answer, i really like the way you made this project.
