### ISSUE TITLE
Dynamic Select2 in popup modal

### ISSUE THREAD

**Issue by bisnard29** [dimkoug/tododjangoccb#8]
hi,
I am struggling to  change classic select with more dynamic selelct2 in the popup form.
how would you advise to adapt?
Thanks,

**Comment by bisnard29** [comment]
something like this 
![image](https://user-images.githubusercontent.com/58581090/81328270-e46f0380-909c-11ea-91dc-06389b36463e.png)

**Comment by dimkoug** [comment]
check this plugin https://select2.org/getting-started/basic-usage
